# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
  echo "#{ENV['AWS_ACCESS_KEY_ID']}:#{ENV['AWS_SECRET_ACCESS_KEY']}" | sudo tee -a /etc/passwd-s3fs
  sudo chmod 640 /etc/passwd-s3fs
SCRIPT

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "aws-dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.keypair_name = ENV['AWS_KEYPAIR_NAME']

    aws.instance_type = 't2.micro'
    aws.region = 'us-east-1'
    #aws.availability_zone = "us-east-1a"
    aws.ami = 'ami-76817c1e'
    aws.subnet_id = "subnet-fcfb288b"

    aws.security_groups = ['sg-8d735ae8']
    aws.tags = {
      'Name' => 'vagrant for mixer2.org'
    }

    # Device Mapping
    aws.block_device_mapping = [
      {
        'DeviceName' => '/dev/xvda',
        'Ebs.DeleteOnTermination' => true,
        'Ebs.VolumeSize' => 8
      }
    ]

    override.ssh.pty = true
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = ENV['SSH_PRIVATE_KEY_PATH']
  end
  config.vm.provision :shell, :inline => $script
  config.vm.provision :shell do |shell|
       shell.path = "s3fs.sh"
  end
end

